name: Build and Deploy NodeJS App on AWS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: ci-cd-pipeline
  ECS_CLUSTER: ci-cd-cluster
  ECS_SERVICE: ci-cd-service

jobs:
  Build-App:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::254771353010:role/GitHubActionsECSDeployRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build \
            -t 254771353010.dkr.ecr.us-east-1.amazonaws.com/ci-cd-pipeline:latest .

      - name: Push Docker Image to ECR
        run: |
          docker push \
            254771353010.dkr.ecr.us-east-1.amazonaws.com/ci-cd-pipeline:latest

      - name: Deploy Updated Image to ECS
        run: |
          aws ecs update-service \
            --cluster "$ECS_CLUSTER" \
            --service "$ECS_SERVICE" \
            --force-new-deployment

      - name: Wait for ECS Service Stability
        run: |
          aws ecs wait services-stable \
            --cluster "$ECS_CLUSTER" \
            --services "$ECS_SERVICE"
